// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wQ4oDWPvgcS0UmlE8ZtvFfw54Z1nuLU',
    appId: '1:1032765106469:web:09646e8b52473811a712cc',
    messagingSenderId: '1032765106469',
    projectId: 'shop-pet-project',
    authDomain: 'shop-pet-project.firebaseapp.com',
    storageBucket: 'shop-pet-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vX8iZvdyygQrA8j58rLOlaU7yMKNdEk',
    appId: '1:1032765106469:android:f2ae4c873a034ff8a712cc',
    messagingSenderId: '1032765106469',
    projectId: 'shop-pet-project',
    storageBucket: 'shop-pet-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC33xm9VC02b1AJzBvKrYyqvZo8q35t3q4',
    appId: '1:1032765106469:ios:9edf10e37a9014b4a712cc',
    messagingSenderId: '1032765106469',
    projectId: 'shop-pet-project',
    storageBucket: 'shop-pet-project.appspot.com',
    iosClientId: '1032765106469-8o9eef07795ngljm9b4n1udrj31vog8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPetProjectShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC33xm9VC02b1AJzBvKrYyqvZo8q35t3q4',
    appId: '1:1032765106469:ios:9edf10e37a9014b4a712cc',
    messagingSenderId: '1032765106469',
    projectId: 'shop-pet-project',
    storageBucket: 'shop-pet-project.appspot.com',
    iosClientId: '1032765106469-8o9eef07795ngljm9b4n1udrj31vog8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPetProjectShop',
  );
}
